import Head from 'next/head'
import AppLayout from '../components/AppLayout'
import Header from '../components/Header'
import FeaturedProduct from '../components/FeaturedProduct'
import ProductList from '../components/ProductList'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <Header />
        <FeaturedProduct />
        <ProductList />
      </AppLayout>

      <style jsx>{`
        h1 {
          text-align: center;
          font-size: 1.5em;
        }
        nav {
          text-align: center;
          font-size: 24px;
        }
      `}
      </style>
    </div>
  )
}
