import Head from 'next/head'
import Link from 'next/link'
import AppLayout from '../components/AppLayout'
import Header from '../components/Header'
import { useEffect, useState } from 'react'

import { getFirestore } from '../firebase/client'

export default function Home() {
  const [products, setProducts] = useState([])
  const dbQuery = getFirestore()
  const traer = dbQuery.collection('products')
  useEffect(() => {
    traer.get().then(({ docs }) => {
      setProducts(
        docs.map(doc => ({ id: doc.id, ...doc.data() })))
    })
  }, [])
  
  console.log(products)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <Header />
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <nav>
          <Link href="/timeline">
            <a>
              timeline
            </a>
          </Link>
        </nav>
      </AppLayout>

      <style jsx>{`
        h1 {
          text-align: center;
          font-size: 1.5em;
        }
        nav {
          text-align: center;
          font-size: 24px;
        }
      `}
      </style>
    </div>
  )
}
